export const __SET_CHOICE = "ENGLISH_WORD_TEST/__SET_CHOICE";
export const __LOCK_AND_SHOW = "ENGLISH_WORD_TEST/__LOCK_AND_SHOW";
export const __UNLOCK_AND_HIDE = "ENGLISH_WORD_TEST/__UNLOCK_AND_HIDE"

export const __ASYNC_SUBMIT_QUESTIONS = {
  pending: "ENGLISH_WORD_TEST/__SUBMIT_QUESTIONS_PENDING",
  resolved: "ENGLISH_WORD_TEST/__SUBMIT_QUESTIONS_RESOVLED",
  rejected: "ENGLISH_WORD_TEST/__SUBMIT_QUESTIONS_REJECTED",
};

export const __ASYNC_LOAD_QUESTIONS = {
  pending: "ENGLISH_WORD_TEST/__LOAD_QUESTIONS_PENDING",
  resolved: "ENGLISH_WORD_TEST/__LOAD_QUESTIONS_RESOVLED",
  rejected: "ENGLISH_WORD_TEST/__LOAD_QUESTIONS_REJECTED",
};

export const __RECORD_WORD_TEST = {
  pending: "ENGLISH_WORD_TEST/__RECORD_WORD_TEST_PENDING",
  resolved: "ENGLISH_WORD_TEST/__RECORD_WORD_TEST_RESOVLED",
  rejected: "ENGLISH_WORD_TEST/__RECORD_WORD_TEST_REJECTED",
};

export const __NEXT = "ENGLISH_WORD_TEST/__NEXT";
export const __AUTO_NEXT = "ENGLISH_WORD_TEST/__AUTO_NEXT";
export const __FORCE_END = "ENGLISH_WORD_TEST/__FORCE_END";
