export const __SET_LEARNING_TYPE = "LEARNING_TYPE/__SET_LEARNING_TYPE";
export const __RECORD_XINGSHI_OR_LUNZHENG = "XINGSHI_LUNZHENG_TYPE/__RECORD_XINGSHI_OR_LUNZHENG";
export const __ASYNC_LOAD_CHAPTER_NAME = {
  pending: "CHAPTERNAME/__LOAD_CHAPTER_NAME_PENDING",
  resolved: "CHAPTERNAME/__LOAD_CHAPTER_NAME_RESOLVED",
  rejected: "CHAPTERNAME/__LOAD_CHAPTER_NAME_REJECTED"
};
export const __ASYNC_SUBMIT_WHETHER_NEXT = {
  pending: "WHETHERNEXT/__SUBMIT_WHETHER_NEXT_PENDING",
  resolved: "WHETHERNEXT/__SUBMIT_WHETHER_NEXT_RESOLVED",
  rejected: "WHETHERNEXT/__SUBMIT_WHETHER_NEXT_REJECTED"
};
