export const __RECORD_USER_INPUT_TEXT = "EDIT_TEXT/__RECORD_USER_INPUT_TEXT";

export const __SAVE_OR_SUMBIT_TEXT = {
  pending: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_PENDING",
  resolved: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_RESOVLED",
  rejected: "EDIT_TEXT/__SAVE_OR_SUMBIT_TEXT_REJECTED",
};
export const __LOAD_LAST_SAVE_TEXT = {
  pending: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_PENDING",
  resolved: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_RESOVLED",
  rejected: "EDIT_TEXT/__LOAD_LAST_SAVE_TEXT_REJECTED",
};
