export const __LOAD_DID_TEST = {
  pending: "ENGLISH_LEARNING_TYPE_PORT/__LOAD_DID_TEST_PENDING",
  resolved: "ENGLISH_LEARNING_TYPE_PORT/__LOAD_DID_TEST_RESOVLED",
  rejected: "ENGLISH_LEARNING_TYPE_PORT/__LOAD_DID_TEST_REJECTED",
};
