export const __LOAD_ALL_SUBMIT_TEXT = {
  pending: "VIEW_FINISHED_TEXT/__LOAD_ALL_SUBMIT_TEXT_PENDING",
  resolved: "VIEW_FINISHED_TEXT/__LOAD_ALL_SUBMIT_TEXT_RESOVLED",
  rejected: "VIEW_FINISHED_TEXT/__LOAD_ALL_SUBMIT_TEXT_REJECTED",
};

export const __RECORD_USER_CHOSED_WHICH_TEXT_TO_VIEW = "VIEW_FINISHED_TEXT/__RECORD_USER_CHOSED_WHICH_TEXT_TO_VIEW";

export const __RESET_USER_CHOSED_WHICH_TEXT_TO_VIEW = "VIEW_FINISHED_TEXT/__RESET_USER_CHOSED_WHICH_TEXT_TO_VIEW";
