export const __SET_ZHONGDIAN_SUBMIT_STATE = "LOGIC_STATE/__SET_ZHONGDIAN_SUBMIT_STATE";
export const __SET_QIANGHUA_SUBMIT_STATE = "LOGIC_STATE/__SET_QIANGHUA_SUBMIT_STATE";
export const __SET_UNITTEST_SUBMIT_STATE = "LOGIC_STATE/__SET_UNITTEST_SUBMIT_STATE";
